import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { designFont, primaryFont, secondaryFont } from "./fonts";
import { CartProvider } from "@/contexts/CartContext";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import { WishlistProvider } from "@/contexts/WishlistContext";
import { FollowProvider } from "@/contexts/FollowContext";

export const metadata: Metadata = {
  title: "Kyzat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} ${designFont.variable} font-primary antialiased`}
        style={{ colorScheme: "light" }}
        // suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          enableColorScheme
          disableTransitionOnChange
        >
          <NextTopLoader
            color="var(--primary)"
            showSpinner={false}
            easing="ease"
          />
          <Toaster richColors position={"top-right"} />
          <FollowProvider>
            <WishlistProvider>
              <CartProvider>{children}</CartProvider>
            </WishlistProvider>
          </FollowProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
